"""add driver license expiry

Revision ID: 0103d0908f74
Revises: deec24ae1608
Create Date: 2026-02-13 13:01:35.460410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0103d0908f74'
down_revision = 'deec24ae1608'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('license_expiry', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.drop_column('license_expiry')

    # ### end Alembic commands ###
