"""fuel entry company share percent and amount

Revision ID: 31062738de08
Revises: d6d60e066324
Create Date: 2026-02-13 15:29:25.871194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31062738de08'
down_revision = 'd6d60e066324'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_share_pct', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('company_amount', sa.Numeric(precision=12, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_entries', schema=None) as batch_op:
        batch_op.drop_column('company_amount')
        batch_op.drop_column('company_share_pct')

    # ### end Alembic commands ###
