"""vehicle bookings

Revision ID: 3d6ea57cdda2
Revises: 8309c03fe49f
Create Date: 2026-02-13 19:43:58.798877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d6ea57cdda2'
down_revision = '8309c03fe49f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('employee_name', sa.String(length=120), nullable=False),
    sa.Column('department', sa.String(length=120), nullable=True),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('purpose', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'CANCELLED', 'COMPLETED', name='bookingstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicle_bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_bookings_end_at'), ['end_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_bookings_start_at'), ['start_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_bookings_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_bookings_vehicle_id'), ['vehicle_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_bookings_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_vehicle_bookings_status'))
        batch_op.drop_index(batch_op.f('ix_vehicle_bookings_start_at'))
        batch_op.drop_index(batch_op.f('ix_vehicle_bookings_end_at'))

    op.drop_table('vehicle_bookings')
    # ### end Alembic commands ###
