"""trip closure odometer times

Revision ID: 8309c03fe49f
Revises: 8cf57c638b20
Create Date: 2026-02-13 15:50:05.545149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8309c03fe49f'
down_revision = '8cf57c638b20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('odometer_start', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('odometer_end', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('time_out', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('time_in', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_column('time_in')
        batch_op.drop_column('time_out')
        batch_op.drop_column('odometer_end')
        batch_op.drop_column('odometer_start')

    # ### end Alembic commands ###
