"""trip expenses toll other

Revision ID: 8cf57c638b20
Revises: 31062738de08
Create Date: 2026-02-13 15:31:15.324444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cf57c638b20'
down_revision = '31062738de08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('expense_type', sa.Enum('TOLL', 'OTHER', name='tripexpensetype'), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('attachment_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trip_expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trip_expenses_expense_date'), ['expense_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_trip_expenses_expense_type'), ['expense_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_trip_expenses_trip_id'), ['trip_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trip_expenses_trip_id'))
        batch_op.drop_index(batch_op.f('ix_trip_expenses_expense_type'))
        batch_op.drop_index(batch_op.f('ix_trip_expenses_expense_date'))

    op.drop_table('trip_expenses')
    # ### end Alembic commands ###
