"""fuel log driver

Revision ID: ba585be89d4b
Revises: 09e7338d3335
Create Date: 2026-02-13 12:20:14.694993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba585be89d4b'
down_revision = '09e7338d3335'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('driver_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_fuel_logs_driver_id'), ['driver_id'], unique=False)
        batch_op.create_foreign_key('fk_fuel_logs_driver_id_drivers', 'drivers', ['driver_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_logs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_fuel_logs_driver_id_drivers', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_fuel_logs_driver_id'))
        batch_op.drop_column('driver_id')

    # ### end Alembic commands ###
