"""add fuel entries vehicle docs notifications maintenance plans wo items incidents

Revision ID: d6d60e066324
Revises: e9995d627534
Create Date: 2026-02-13 15:06:39.901581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6d60e066324'
down_revision = 'e9995d627534'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_no', sa.String(length=80), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('incident_dt', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('incident_type', sa.Enum('ACCIDENT', 'DAMAGE', 'THEFT', 'OTHER', name='incidenttype'), nullable=False),
    sa.Column('severity', sa.Enum('MINOR', 'MAJOR', 'TOTAL_LOSS', name='incidentseverity'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('REPORTED', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'CLOSED', name='incidentstatus'), nullable=False),
    sa.Column('approver_user_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approval_note', sa.Text(), nullable=True),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('claim_no', sa.String(length=120), nullable=True),
    sa.Column('claim_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'PAID', name='claimstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approver_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incidents_approver_user_id'), ['approver_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_incident_dt'), ['incident_dt'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_incident_no'), ['incident_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_incidents_incident_type'), ['incident_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_vehicle_id'), ['vehicle_id'], unique=False)

    op.create_table('maintenance_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('schedule_mode', sa.Enum('KM', 'TIME', 'BOTH', name='schedulemode'), nullable=False),
    sa.Column('interval_km', sa.Integer(), nullable=True),
    sa.Column('interval_days', sa.Integer(), nullable=True),
    sa.Column('last_service_meter', sa.Integer(), nullable=True),
    sa.Column('last_service_date', sa.Date(), nullable=True),
    sa.Column('next_due_meter', sa.Integer(), nullable=True),
    sa.Column('next_due_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maintenance_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_plans_next_due_date'), ['next_due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_plans_vehicle_id'), ['vehicle_id'], unique=False)

    op.create_table('vehicle_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.Enum('INSURANCE', 'FITNESS', 'REGISTRATION', 'PERMIT', 'TAX', name='vehicledoctype'), nullable=False),
    sa.Column('doc_name', sa.String(length=160), nullable=True),
    sa.Column('doc_number', sa.String(length=120), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='vehicledocstatus'), nullable=False),
    sa.Column('attachment_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicle_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_documents_doc_type'), ['doc_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_documents_expiry_date'), ['expiry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_documents_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_documents_vehicle_id'), ['vehicle_id'], unique=False)

    op.create_table('fuel_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('slip_no', sa.String(length=80), nullable=False),
    sa.Column('fuel_date', sa.Date(), nullable=False),
    sa.Column('odometer_at_fuel', sa.Integer(), nullable=True),
    sa.Column('liters', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rate', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('fuel_type', sa.Enum('OFFICIAL', 'PERSONAL', name='fueltype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='fuelentrystatus'), nullable=False),
    sa.Column('verified_by_user_id', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('attachment_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fuel_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fuel_entries_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fuel_entries_fuel_date'), ['fuel_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_fuel_entries_fuel_type'), ['fuel_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_fuel_entries_slip_no'), ['slip_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_fuel_entries_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_fuel_entries_trip_id'), ['trip_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fuel_entries_vehicle_id'), ['vehicle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fuel_entries_verified_by_user_id'), ['verified_by_user_id'], unique=False)

    op.create_table('incident_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incident_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incident_attachments_incident_id'), ['incident_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('DOC_EXPIRY', 'DOC_MISSING', 'PM_DUE', 'WO_OVERDUE', 'FUEL_PENDING', 'INCIDENT_PENDING', name='notificationtype'), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('doc_id', sa.Integer(), nullable=True),
    sa.Column('wo_id', sa.Integer(), nullable=True),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='notificationseverity'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('dismissed_until', sa.DateTime(), nullable=True),
    sa.Column('last_shown_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['vehicle_documents.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.ForeignKeyConstraint(['wo_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_doc_id'), ['doc_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_trip_id'), ['trip_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_vehicle_id'), ['vehicle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_wo_id'), ['wo_id'], unique=False)

    op.create_table('work_order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wo_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('subsystem', sa.String(length=80), nullable=True),
    sa.Column('component', sa.String(length=120), nullable=True),
    sa.Column('job_type', sa.Enum('REPAIR', 'REPLACE', 'SERVICE', 'INSPECT', name='jobtype'), nullable=False),
    sa.Column('detail_text', sa.Text(), nullable=True),
    sa.Column('labor_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('parts_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('attachment_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['wo_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_order_items_wo_id'), ['wo_id'], unique=False)

    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wo_no', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('wo_type', sa.Enum('PREVENTIVE', 'BREAKDOWN', 'ACCIDENT', name='workordertype'), nullable=False))
        batch_op.add_column(sa.Column('work_source', sa.Enum('INTERNAL', 'EXTERNAL', name='worksource'), nullable=False))
        batch_op.add_column(sa.Column('vehicle_in_workshop_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('vehicle_out_workshop_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('odometer_in', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('odometer_out', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('vendor_name', sa.String(length=160), nullable=True))
        batch_op.create_index(batch_op.f('ix_work_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_orders_wo_no'), ['wo_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_work_orders_wo_type'), ['wo_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_orders_work_source'), ['work_source'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_orders_work_source'))
        batch_op.drop_index(batch_op.f('ix_work_orders_wo_type'))
        batch_op.drop_index(batch_op.f('ix_work_orders_wo_no'))
        batch_op.drop_index(batch_op.f('ix_work_orders_status'))
        batch_op.drop_column('vendor_name')
        batch_op.drop_column('odometer_out')
        batch_op.drop_column('odometer_in')
        batch_op.drop_column('vehicle_out_workshop_at')
        batch_op.drop_column('vehicle_in_workshop_at')
        batch_op.drop_column('work_source')
        batch_op.drop_column('wo_type')
        batch_op.drop_column('wo_no')

    with op.batch_alter_table('work_order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_order_items_wo_id'))

    op.drop_table('work_order_items')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_wo_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_type'))
        batch_op.drop_index(batch_op.f('ix_notifications_trip_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_incident_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_due_date'))
        batch_op.drop_index(batch_op.f('ix_notifications_doc_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('incident_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incident_attachments_incident_id'))

    op.drop_table('incident_attachments')
    with op.batch_alter_table('fuel_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fuel_entries_verified_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_fuel_entries_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_fuel_entries_trip_id'))
        batch_op.drop_index(batch_op.f('ix_fuel_entries_status'))
        batch_op.drop_index(batch_op.f('ix_fuel_entries_slip_no'))
        batch_op.drop_index(batch_op.f('ix_fuel_entries_fuel_type'))
        batch_op.drop_index(batch_op.f('ix_fuel_entries_fuel_date'))
        batch_op.drop_index(batch_op.f('ix_fuel_entries_driver_id'))

    op.drop_table('fuel_entries')
    with op.batch_alter_table('vehicle_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_documents_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_vehicle_documents_status'))
        batch_op.drop_index(batch_op.f('ix_vehicle_documents_expiry_date'))
        batch_op.drop_index(batch_op.f('ix_vehicle_documents_doc_type'))

    op.drop_table('vehicle_documents')
    with op.batch_alter_table('maintenance_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_plans_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_maintenance_plans_next_due_date'))

    op.drop_table('maintenance_plans')
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incidents_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_incidents_status'))
        batch_op.drop_index(batch_op.f('ix_incidents_severity'))
        batch_op.drop_index(batch_op.f('ix_incidents_incident_type'))
        batch_op.drop_index(batch_op.f('ix_incidents_incident_no'))
        batch_op.drop_index(batch_op.f('ix_incidents_incident_dt'))
        batch_op.drop_index(batch_op.f('ix_incidents_driver_id'))
        batch_op.drop_index(batch_op.f('ix_incidents_approver_user_id'))

    op.drop_table('incidents')
    # ### end Alembic commands ###
