"""vehicle current driver

Revision ID: deec24ae1608
Revises: ba585be89d4b
Create Date: 2026-02-13 12:23:50.718042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deec24ae1608'
down_revision = 'ba585be89d4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_driver_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_vehicles_current_driver_id'), ['current_driver_id'], unique=False)
        batch_op.create_foreign_key('fk_vehicles_current_driver_id_drivers', 'drivers', ['current_driver_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_constraint('fk_vehicles_current_driver_id_drivers', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_vehicles_current_driver_id'))
        batch_op.drop_column('current_driver_id')

    # ### end Alembic commands ###
