"""phase1 trip fields usage dept employee destination city items return

Revision ID: e9995d627534
Revises: 0103d0908f74
Create Date: 2026-02-13 13:18:33.406904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9995d627534'
down_revision = '0103d0908f74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usage_type', sa.Enum('OFFICIAL', 'PERSONAL', 'MEDICAL_EMERGENCY', 'SCHOOL', 'EDUCATIONAL', name='usagetype'), nullable=False))
        batch_op.add_column(sa.Column('department', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('employee_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('destination_city', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('carrying_items', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('items_owner', sa.Enum('PERSONAL', 'COMPANY', name='itemsowner'), nullable=True))
        batch_op.add_column(sa.Column('gatepass_no', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('items_reason', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('items_details', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('items_return_status', sa.Enum('RETURNED', 'NOT_RETURNED', 'PARTIAL', name='itemsreturnstatus'), nullable=True))
        batch_op.add_column(sa.Column('items_not_returned_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('items_expected_return_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_column('items_expected_return_date')
        batch_op.drop_column('items_not_returned_reason')
        batch_op.drop_column('items_return_status')
        batch_op.drop_column('items_details')
        batch_op.drop_column('items_reason')
        batch_op.drop_column('gatepass_no')
        batch_op.drop_column('items_owner')
        batch_op.drop_column('carrying_items')
        batch_op.drop_column('destination_city')
        batch_op.drop_column('employee_name')
        batch_op.drop_column('department')
        batch_op.drop_column('usage_type')

    # ### end Alembic commands ###
